##--------------------------------------------------------------------
## rmqtt-http-web
##--------------------------------------------------------------------

##Number of worker threads
workers = 1
## Max Row Limit
max_row_limit = 10_000
## HTTP Listener
http_laddr = "0.0.0.0:4080"


